/***************************************************************************************************
 * CALLBACK Funktion aus bol-globals.js, welche in diesem Projekt verwendet werden
 * zeigt entsprechende Hilfetexte je Feld an
***************************************************************************************************/

// Standard-Strings fuer Meldungen innerhalb der Bibliothek
export const bol__project_strings = [
    {msglng: "de", msgid: "hlp_operator", msg: "Der Begriff des Betreibers beschreibt, wer rechtlich für den Anlagenbetrieb verantwortlich ist. Dies kann eine natürliche Person oder auch eine juristische Person (z.B. eine AG oder GmbH) sein. Ein Betreiber kann eine oder mehrere Betriebsstätten haben."},
    {msglng: "de", msgid: "hlp_operator.name", msg: "Bitte nennen Sie den offiziellen Namen, zum Beispiel der Firma."},
    {msglng: "de", msgid: "hlp_operator.address", msg: "Bitte geben Sie die offizielle Anschrift des Betreibers an."},

    {msglng: "de", msgid: "hlp_operatingSite", msg: "Die Betriebsstätte steht für alle Anlagen eines Betreibers an einem Standort. Wenn Sie  mehrere Anlagen an einem Ort betreiben, haben diese Anlagen i.d.R. eine identische Betriebsstätten-Nummer."},
    {msglng: "de", msgid: "hlp_operatingSite.name", msg: "Bitte nennen Sie den Namen der Betriebsstätte, zum Beispiel des Firmenstandorts."},
    {msglng: "de", msgid: "hlp_operatingSite.nr", msg: "Die Betriebsstätten-Nummer, auch Arbeitsstätten-Nummer genannt, erhalten Sie von der zuständigen Aufsichtsbehörde. Sie identifiziert Ihre Betriebsstätte eindeutig."},
    {msglng: "de", msgid: "hlp_operatingSite.naceCode.code", msg: "Die Nomenklatur der Wirtschaftstätigkeiten (NACE) ist die europäische statistische Klassifikation der Wirtschaftstätigkeiten. Bitte geben Sie Ihren passenden NACE-Code ein. Die Übersicht finden Sie unter folgendem <a href='https://ec.europa.eu/eurostat/documents/3859598/5902453/KS-RA-07-015-DE.PDF' target='_blank'> Link </a>."},
    {msglng: "de", msgid: "hlp_operatingSite.address", msg: "Bitte geben Sie die offizielle Anschrift der Betriebsstätte an, falls diese zu den Angaben zum Betreiber abweicht."},

    {msglng: "de", msgid: "hlp_plant.name", msg: "Die Anlagenbezeichnung wurde betriebsintern festgelegt. Sie können sie i.d.R. auch dem Genehmigungsbescheid für die Anlage entnehmen."},
    {msglng: "de", msgid: "hlp_plant.nr", msg: "Die Anlagennummer dient der Identifikation einer Anlage bzw. der systematischen Unterscheidung von mehreren Anlagen innerhalb eines Standortes. Sie wird i.d.R. in den Formularen zum Genehmigungsantrag angegeben."},
    {msglng: "de", msgid: "hlp_plant.approvalNumber67", msg: "Das Aktenzeichen der Genehmigungsbehörde finden Sie auf dem ersten Genehmigungsbescheid Ihrer Anlage oder dem Feststellungsbescheid bei einer Anzeige nach § 67, ggf. in Verbindung mit einer Anordnung nach § 17 des Bundes-Immissionsschutzgesetzes."},   
    {msglng: "de", msgid: "hlp_plant.nrAccordingToAppendix1Of4BImSchV", msg: "Bitte geben Sie die Nummer der genehmigungsbedürftigen Anlage nach Anhang 1 der 4. Verordnung zur Durchführung des Bundes-Immissionsschutzgesetzes (<a href='http://www.gesetze-im-internet.de/bimschv_4_2013/anhang_1.html' target='_blank'>BImSchV</a>) an. <br>Sie finden diese Nummer in Ihrer Genehmigung."},
    {msglng: "de", msgid: "hlp_plant.nrAccordingToIEDirective", msg: "Bitte geben Sie die Nummer der Tätigkeit nach Anhang I der Industrieemissionsrichtlinie 2010/75/EU (IED) der Europäischen Union an. <a href='https://eur-lex.europa.eu/legal-content/DE/TXT/?uri=uriserv%3AOJ.L_.2010.334.01.0017.01.DEU&toc=OJ%3AL%3A2010%3A334%3ATOC' target='_blank'> Link</a>."},
    {msglng: "de", msgid: "hlp_plant.nrAccordingToPRTR", msg: "Bitte geben Sie die Nummer der Tätigkeit nach Anhang I der Verordnung (EG) Nr. 166/2006 über die Schaffung eines Europäischen Schadstofffreisetzungs- und -verbringungsregisters (Pollutant Release and Transfer Register, PRTR). <a href='https://thru.de/fileadmin/SITE_MASTER/content/Dokumente/Downloads/E-PRTR-VO_dt.pdf' target='_blank'>Link</a>."},
    {msglng: "de", msgid: "hlp_plant.registryCode", msg: "Falls Ihre Anlage unter die  europäische Emissionshandelsrichtlinie 2003/87/EG, geben Sie bitte die eindeutige Registerkennung im EU-Transaktionsprotokoll an. <a href='https://eur-lex.europa.eu/legal-content/DE/TXT/PDF/?uri=OJ:L:2020:423:FULL&from=FR' target='_blank'>Link</a><br> Sie finden die Kennung in Ihrer Genehmigung zur Anlage."},
    {msglng: "de", msgid: "hlp_plant.eastValue", msg: "Bitte geben Sie die Koordinaten nach dem Europäischen Terrestrischen Referenzsystem 1989 (ETRS89) mit UTM (Universale-Transversale Mercatorprojektion) an."},
    {msglng: "de", msgid: "hlp_plant.northValue", msg: "Bitte geben Sie die Koordinaten nach dem Europäischen Terrestrischen Referenzsystem 1989 (ETRS89) mit UTM (Universale-Transversale Mercatorprojektion) an."},



    {msglng: "de", msgid: "hlp_operatorPerson", msg: "Gemeint ist die vertretungsberechtigte Person."},
    {msglng: "de", msgid: "hlp_operatingsiteperson", msg: "Falls die Angaben von der Person abweichen, die Sie unter 'Ansprechperson zum Betreiber' angegeben haben: Bitte nennen Sie den Namen und die Funktion der Person, die für den Betriebsbereich verantwortlich ist. Diese Anzeige legt § 7 der Störfall-Verordnung.<br> zum <a href='http://www.gesetze-im-internet.de/bimschv_12_2000/__7.html' target='_blank'>Gesetz</a>"},

    {msglng: "de", msgid: "hlp_plantDateStart", msg: "Bitte geben Sie das Datum der Inbetriebnahme oder falls es sich um keine neue Anlage, sondern um eine bestehende Anlage handelt, das Datum dieser Anzeige an."},
    {msglng: "de", msgid: "hlp_plantAuthority", msg: "Wenn sich die zuständige Behörde von der Behörde zur Betriebsstätte unterscheidet, wählen Sie bitte die abweichende Behörde zur Anlage aus."},
    {msglng: "de", msgid: "hlp_plantGemarkung", msg: "Gemarkungen bestehen aus einigen Grund- beziehungsweise Flurstücken. Im Grundbuch finden Sie die Eigentumsverhältnisse von einzelnen Gemarkungen."},
    
    {msglng: "de", msgid: "hlp_plantCategory", msg: "Wenn Sie eine nicht genehmigungsbedürftige, ortsfeste Anlage betreiben, müssen Sie diese Anlagenkategorie Ihrer zuständigen Behörde anzeigen, bevor Sie die Anlage in Betrieb nehmen. <br> zum <a href='https://www.gesetze-im-internet.de/bimschv_20_1998/__8.html' target='_blank'>Gesetz</a>"},
    {msglng: "de", msgid: "hlp_plantpart", msg: "Nebeneinrichtungen dienen dem Anlagenzweck und stehen im räumlichen oder betriebstechnischen Zusammenhang mit der Hauptanlage. Sie sind jedoch für den bestimmungsgemäßen Betrieb nicht erforderlich. Es handelt sich zum Beispiel um Lager oder Aufbereitungseinrichtungen, die schädliche Umwelteinwirkungen haben können oder sonstige Gefahren darstellen.<br> zur <a href='https://www.gesetze-im-internet.de/bimschv_4_2013/__1.html' target='_blank'>4. Verordnung zur Durchführung des Bundes-Immissionsschutzgesetzes</a>"},
    {msglng: "de", msgid: "hlp_plantBetriebseinheit", msg: "Die Anlage sowie Anlagenteile sind in Betriebseinheiten unterteilt, die eine oder mehrere gleichartige Teilanlagen, einen oder mehrere gleichartige Anlagenteile oder einen oder mehrere gleichartige Verfahrensabschnitte umfassen können. Bitte geben Sie besonders Betriebseinheiten an, die selbstständig Emissionen verursachen."},

    {msglng: "de", msgid: "hlp_plantAddress", msg: "Falls die Angaben zur Adresse der Betriebsstätte abweichen, geben Sie bitte die abweichende Adresse der Anlage hier ein."},
    {msglng: "de", msgid: "hlp_plantPerson", msg: "Falls die Angaben zur Ansprechperson der Betriebsstätte abweichen, geben Sie bitte die abweichende Ansprechperson zur Betriebsstätte ein."},
    {msglng: "de", msgid: "hlp_plantBImSchV124", msg: "Die 4. Verordnung zur Durchführung des Bundes-Immissionsschutzgesetzes <a href='http://www.gesetze-im-internet.de/bimschv_4_2013/anhang_1.html' target='_blank'>(4. BImSchV), § 1, Absatz 2</a>, legt genau fest, welche Anlagen eine Genehmigung benötigen. "},
    {msglng: "de", msgid: "hlp_plantAggregiert", msg: "Ihre Feuerungsanlage bildet mit weiteren Feuerungsanlagen eine gemeinsame, also aggregierte Anlage, wenn Sie Abgase über einen gemeinsamen Schornstein ableiten (können). Weitere Informationen finden Sie in <a href='https://www.bmuv.de/gesetz/44-verordnung-zur-durchfuehrung-des-bundes-immissionsschutzgesetzes' target='_blank'>§ 4 der 44. Verordnung</a> zur Durchführung des Bundes-Immissionsschutzgesetzes (44. BImSchV). "},
    {msglng: "de", msgid: "hlp_plantAggregiertAnzahl", msg: "Einzelfeuerungen sind Feuerungsanlagen, die im Gegensatz zu aggregierten Anlagen eine gesonderte, einzelne Anlage darstellen."},
    {msglng: "de", msgid: "hlp_plantAggregiertLeistung", msg: "Wenn Ihre Anlage eine aggregierte Anlage ist, ergibt sich der Wert (in Megawatt, MW) aus der gesamten Feuerungswärmeleistung der verbundenen Feuerungsanlagen."},

    {msglng: "de", msgid: "hlp_plantWenigeBetriebsstunden", msg: "Sie haben eine Erklärung unterzeichnet, nach welcher die Feuerungsanlage nicht mehr Stunden in Betrieb ist als angegeben. <a href='https://www.gesetze-im-internet.de/bimschv_44/BJNR080410019.html' target='_blank'>Zum Gesetz, 44. Verordnung zur Durchführung des Bundes-Immissionsschutzgesetzes</a>"},
    {msglng: "de", msgid: "hlp_plantNotbetrieb", msg: "Sie haben eine Erklärung unterzeichnet, nach welcher die Feuerungsanlage nur im Notfall in Betrieb ist. <a href='https://www.gesetze-im-internet.de/bimschv_44/BJNR080410019.html' target='_blank'>Zum Gesetz, 44. Verordnung zur Durchführung des Bundes-Immissionsschutzgesetzes</a>"},

    {msglng: "de", msgid: "hlp_emissionSource", msg: "Die Angabe betrifft eine Emissionsquelle, zum Beispiel einen Schornstein, über den die Abgase der Anlage abgeleitet werden."},        
    {msglng: "de", msgid: "hlp_emissionSourceEast", msg: "Bitte geben Sie die Koordinaten nach dem Europäischen Terrestrischen Referenzsystem 1989 (ETRS89) mit UTM (Universale-Transversale Mercatorprojektion) an."},
    {msglng: "de", msgid: "hlp_emissionSourceNorth", msg: "Bitte geben Sie die Koordinaten nach dem Europäischen Terrestrischen Referenzsystem 1989 (ETRS89) mit UTM (Universale-Transversale Mercatorprojektion) an."},

    // obsolete?
    {msglng: "de", msgid: "hlp_plantBImSchG", msg: "Anlagen, die nach der 4. Verordnung zur Durchführung des Bundes-Immissionsschutzgesetzes (4. BImSchV) eine Genehmigung brauchen, gelten als „genehmigungsbedürftige Anlagen“. Die 4. BImSchV legt fest, welche Anlagen eine Genehmigung benötigen. (Zum <a href='http://www.gesetze-im-internet.de/bimschv_4_2013/anhang_1.html' target='_blank'>Gesetz</a>"},
    {msglng: "de", msgid: "hlp_plantBImSchGnr", msg: "Das Aktenzeichen der Genehmigungsbehörde finden Sie auf dem ersten Genehmigungsbescheid Ihrer Anlage."},

    // especially for Form 31
    {msglng: "de", msgid: "hlp_reportcomment", msg: "Bitte geben Sie zum Beispiel an, wann Sie den Bericht übermittelt haben oder wenn keine Messungen stattgefunden haben."},   
    {msglng: "de", msgid: "hlp_reportcomment2", msg: "Bitte geben Sie zum Beispiel an, wann Sie den Bericht übermittelt haben."},   
    {msglng: "de", msgid: "hlp_measurement.discontinuous.partName", msg: "Bitte geben Sie, auf welche(s) Anlagenteil(e) sich der Bericht bezieht oder ob sich der Bericht auf die gesamte Anlage bezieht."},   
    {msglng: "de", msgid: "hlp_measurement.other", msg: "Falls die für Ihren Standort zuständige Immissionsschutzbehörde weitere Dokumente verlangt, können diese hier hochgeladen werden."},   
    {msglng: "de", msgid: "hlp_measurement.BImSchV13", msg: "Dies betrifft den Jahresbericht nach § 22 der 13. BImSchV. (<a href='https://www.bmuv.de/gesetz/13-verordnung-zur-durchfuehrung-des-bundes-immissionsschutzgesetzes' target='_blanK'>Link</a>)"},            
    {msglng: "de", msgid: "hlp_measurement.BImSchV17", msg: "Dies betrifft den Jahresbericht nach § 22 der 17. BImSchV.(<a href='https://www.bmuv.de/gesetz/17-verordnung-zur-durchfuehrung-des-bundes-immissionsschutzgesetzes' target='_blank'>Link</a>)"},
    {msglng: "de", msgid: "hlp_measurement.BImSchV31", msg: "Dies bezieht sich auf einen Bericht zu Lösemitteln, die der 31. Verordnung zur Durchführung des Bundes-Immissionsschutzgesetzes (31. BImSchV) unterliegen. (<a href='https://www.bmuv.de/gesetz/31-verordnung-zur-durchfuehrung-des-bundes-immissionsschutzgesetzes' target='_blank'>Link)</a>)"},  
    {msglng: "de", msgid: "hlp_measurement.massBalance", msg: "Dies bezieht sich auf eine Berechnung, die der Technischen Anleitung zur Reinhaltung der Luft (TA Luft), Anhang 10, unterliegt. (<a href='https://www.bmuv.de/faqs/technische-anleitung-zur-reinhaltung-der-luft' target='_blank'>Link)</a>)"},  


    {msglng: "de", msgid: "hlp_cycleWaste.BImSchG", msg: "Dies betrifft genehmigungsbedürftige Anlagen, zu denen § 5 (1) Nr. 3 BImSchG Vorgaben macht: Abfälle müssen Sie demnach vermeiden, nicht zu vermeidende Abfälle verwerten und nicht zu verwertende Abfälle ohne Beeinträchtigung des Wohls der Allgemeinheit beseitigen. (<a href='https://www.gesetze-im-internet.de/bimschg/__5.html' target='_blanK'>zum Gesetz)</a>)"},  
    {msglng: "de", msgid: "hlp_other.ISO14001", msg: "Die internationale Umweltmanagementnorm ist der weltweit akzeptierte und angewendete Standard für Umweltmanagementsysteme. (<a href='https://www.umweltbundesamt.de/themen/wirtschaft-konsum/wirtschaft-umwelt/umwelt-energiemanagement/iso-14001-umweltmanagementsystemnorm#inhalte-der-iso-14001' target='_blank'>Weitere Informationen</a>)<br>Das Eco-Management and Audit Scheme (EMAS), auch EU-Öko-Audit, ist das „Gemeinschaftssystem für Umweltmanagement und Umweltbetriebsprüfung“ der Europäischen Union. (<a href=' https://www.emas.de' target='_blank'>Link)</a>)"},  
    {msglng: "de", msgid: "hlp_other.education", msg: "Die Teilnahme an Fortbildungen ist mindestens alle 2 Jahre erforderlich."}, 
    {msglng: "de", msgid: "hlp_other.ISO50001", msg: "Dies bezieht sich auf Nachweise nach dem weltweiten Standards ISO 50001 oder 50005 zum Energiemanagementsystem (<a href='https://www.umweltbundesamt.de/energiemanagementsysteme-iso-50001#iso-50001-aufbau-und-anwendung' target='_blank'>Link</a>) oder Angaben zum Bundes-Immissionsschutzgesetz (BImSchG), § 5, Absatz 1, Nummer 4, dass Sie Energie sparsam und effizient verwenden. (<a href='https://www.gesetze-im-internet.de/bimschg/__5.html' target='_blank'>Zum Gesetz</a>)"}, 

    {msglng: "de", msgid: "hlp_reportevents", msg: "Ereignisse oder Störungen beeinträchtigen den bestimmungsgemäßen Betrieb der Anlage durch einen oder mehrere Gefahrenstoffe. Alle Ereignisse mit schädlichen Umwelteinwirkungen wie Grenzwert-Überschreitungen oder Leckagen müssen Sie angeben. (<a href='https://www.bmuv.de/gesetz/zwoelfte-verordnung-zur-durchfuehrung-des-bundes-immissionsschutzgesetzes' target='_blank'>zum Gesetz</a>)"},  

    {msglng: "de", msgid: "hlp_plant.partName", msg: "Zur Anlage gehören auch alle einzelnen Anlagenteile, die für den Betrieb notwendig und gesondert genehmigungsbedürftig wären. Sie erhalten eine zusätzliche Anlagennummer, zählen aber als Bestandteil der übergeordneten genehmigungsbedürftigen Anlage und benötigen damit keine weitere Genehmigung. Dies ist in der Verordnung über genehmigungsbedürftige Anlagen festgehalten: <a href='http://www.gesetze-im-internet.de/bimschv_4_2013/anhang_1.html' target='_blank'> 4. Verordnung zur Durchführung des Bundes-Immissionsschutzgesetzes (4. BImSchV), § 1, Absatz 4</a>."},
    {msglng: "de", msgid: "hlp_plant.operatingUnit", msg: "Die Anlage sowie Anlagenteile sind in Betriebseinheiten unterteilt, die eine oder mehrere gleichartige Teilanlagen, eine oder mehrere gleichartige Anlagenteile oder einen oder mehrere gleichartige Verfahrensabschnitte umfassen können. Bitte geben Sie insbesondere Betriebseinheiten an, die selbstständig Emissionen erzeugen."},
    {msglng: "de", msgid: "hlp_plant.operatingUnit12BImSchV", msg: "Dies betrifft Anlagen mit gefährlichen Stoffen und störfallrelevanten Betriebsbereichen, die der 12. Verordnung zur Durchführung des Bundes-Immissionsschutzgesetzes (12. BImSchV) unterliegen. (<a href='https://www.bmuv.de/gesetz/zwoelfte-verordnung-zur-durchfuehrung-des-bundes-immissionsschutzgesetzes' target='_blank'>Link</a>)"},

    {msglng: "en", msgid: "key", msg: "value"}
];